package edu.omenyayl.soundpaste.misc

import edu.omenyayl.soundpaste.BuildConfig

class Constants {
    companion object {
        const val CHIRP_CONFIG = "bwQfyrZU+CiKRt5gyH+hgsXbx91zWrTsnf/VbE869by6doCOjb4kKrkuYVwkoBlkDoICLb9GvMXG/mdEynv+ZoI+jA86lqzcmNHLo34FoFIiSWN7qtxEmY8w6D9kq70VphxyctCrS+HEusNQkLF8dYr73bZA66TrujWQFRhRev4VuCyFgDulyVfDYhA5dk/JixHMtMBUGOWA5iRR08PX3bYUwb0hjkhaZcnrNtoF2dkO6TIABjAr28uh1zCpLJ8dX3LDWdEfHo6nBGgKqrfnyMx54umfX5wzIL0O8grqmj9PRVRG72xfoQ92y/kunKV5F5CO/VazSCQhn+c03HTIWT9igClE3nyliU5XWdNRrawded5DtUI6mF4oIPNGsDLQHgwjqgBJkrWz3sENGpDWA223lMwGHGrmhJLvGUhB5Q4zBW6TF1M2KeGVLn/cBg+5uW5eXFQjo3CFfEgEZwaWwm/LyI9uxQn6pzNhwTOKo//KdXzQET0H5VeTFLRksMPVUEpoKcmAQkLGk2a6eTpF4aYZkhH+bEcxLMkVmU2mNJXmXTaevSAKHylXpz5sOyuxHkFdQJk6YjpS9ngG1KFlmg9hiidxvZ2WUwGN1vWcIyo3Dnr2CJhcIila+v1kRHdpg1E4iIMMldkq5fB1B1SkRY+Yx7OPSGlBj11Wiws7fbiGOcCUXLjmdru2swbKOlxP7JtutreWH6uGN8gVOavRvfYBfOhFTurD0rFYtb3KV3nz+VTCSIq45nRWgiFLZ5TFzqRVEP2EFlwrgQblm8TD0gKNZ4YyQ3iBlr585cPpDSEfrfc6sgmxwTwq/exzImKBbTJvpOmWVdbqktXdMRQZoU9rDO7Xx/6y/tZy8XQxeNw="
        const val CHIRP_KEY = BuildConfig.CHIRP_KEY // from local.properties file
        const val CHIRP_SECRET = BuildConfig.CHIRP_SECRET // from local.properties file
    }
}